### ISSUE TITLE
password reset for whichever of my accounts is linked to staging.creativecommons.org

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/communications#10]
please. important one! thanks.

**Comment by mattl** [comment]
Should be your CCID.

**Comment by ericsteuer** [comment]
i thought so too. but it's not working. i even just reset my CCID password just now to see if somehow I was just putting in bad info, but it's still not working.

**Comment by mattl** [comment]
Can you confirm which URL you're using to login?

Also, do you get to the CCID login screen?

**Comment by ericsteuer** [comment]
i'm trying to login via https://staging.creativecommons.org/use-remix/ideas/ to look at a question @little-wow tagged me in.

and yes, i am able to log in at login.creativecommons.org (see screenshot)

<img width="841" alt="screen shot 2016-06-09 at 3 10 53 pm" src="https://cloud.githubusercontent.com/assets/8919762/15948234/74441626-2e54-11e6-85f1-1dea0cc03413.png">

**Comment by mattl** [comment]
Try:

https://staging.creativecommons.org/wordpress/wp-admin

**Comment by ericsteuer** [comment]
doesn't work. i'm trying to login as both "eric" and my full cc email address using the password that works to login at login.cc.org

**Comment by ericsteuer** [comment]
to be clear, i understand my login to be my full email address, but i'm also trying with just "eric" and neither work

**Comment by mattl** [comment]
Can you try another browser? I can login via CCID and I can see your
account in the admin screen.

**Comment by ericsteuer** [comment]
Was using Chrome, now tried Safari (trying both "eric" and my full email address + the password that I'm able to use to log in to login.creativecommons.org. See attached.
<img width="413" alt="screen shot 2016-06-09 at 3 19 47 pm" src="https://cloud.githubusercontent.com/assets/8919762/15948444/add5854a-2e55-11e6-88e7-5fd234e6cdca.png">

**Comment by mattl** [comment]
Okay.

That screen you should not be using your CCID, but the generic password.
I'll email you that now.

**Comment by ericsteuer** [comment]
thank you!

**Comment by mattl** [comment]
Let me know if you're able to login

**Comment by ericsteuer** [comment]
yep, all good. thanks!

**Comment by mattl** [comment]
So when you get a sec, try logging out of CCID in Chrome and trying again
there.
