### ISSUE TITLE
blog post RE: cancer moonshot summit commitments, NCI recommendations

### ISSUE THREAD

**Issue by tvol** [creativecommons/communications#12]

**Comment by tvol** [comment]
hi @little-wow and @ericsteuer I started a draft here: https://docs.google.com/document/d/15ZcpMDgmLa0v2wDt-u2OD4U8AQ20Jn3--tI3h91mwtI/edit

still pretty rough. would appreciate your thoughts about desired order and tone. I think we've discussed that we need to tie in three main things: 1) CC's commitments to the cancer moonshot, 2) our policy recommendations regarding improving access to research, and 3) a story or some personal connection (from the stories we've collected). Anything else? thanks

**Comment by ericsteuer** [comment]
Will take a look right away. One thing, which I almost asked about before -- can you explain to me what you mean by "commitments?" These are commitments we're making, or asking for? If this is made more clear in the draft you sent, never mind -- just couldn't tell from the initial email in this thread what that word meant in this context

**Comment by tvol** [comment]
the "commitments" are something CC is pledging to do, likely through a blood contract, or similar.

**Comment by little-wow** [comment]
I'm conferencing but will take a look tonight

On Wednesday, June 22, 2016, Eric Steuer notifications@github.com wrote:

> Will take a look right away. One thing, which I almost asked about before
> -- can you explain to me what you mean by "commitments?" These are
> commitments we're making, or asking for? If this is made more clear in the
> draft you sent, never mind -- just couldn't tell from the initial email in
> this thread what that word meant in this context
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/creativecommons/communications/issues/12#issuecomment-227911232,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGw-TgCgfy2O9nxtUovun0jInkQfbyJoks5qOcrMgaJpZM4I7SgB
> .

## 

---

Jennie Rose Halperin
Communications Manager
Creative Commons
Invest in an open future. Support Creative Commons today:
http://bit.ly/19IjSKl

**Comment by tvol** [comment]
@little-wow no problem. probably not a huge rush, although I think we should plan on publishing the final version on Monday or Tuesday.

**Comment by tvol** [comment]
hi @ericsteuer @little-wow if you have any edits or feedback, please include them in the doc by noon Monday. thanks
