### ISSUE TITLE
Civi email preheaders?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/communications#13]
We've been sending out emails without specifying the preheader, so they come through like this:
<img width="892" alt="screen shot 2016-06-28 at 12 54 00 pm" src="https://cloud.githubusercontent.com/assets/7093838/16424926/0dfee360-3d30-11e6-864b-dd8e66662398.png">

I can't figure out how to fix this on Civi, and it doesn't belong in the header because it is different for every email, though according to the internet, that's possibly the way to do it.

**Comment by mattl** [comment]
Let's make some time on the calendar tomorrow or next Wed and fix this and other related issues. I'll also show you how to build a form in CiviCRM.
