### ISSUE TITLE
Is this still the email that people get for signing up for the email list?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/communications#18]
<img width="808" alt="screen shot 2016-07-08 at 11 26 50 am" src="https://cloud.githubusercontent.com/assets/7093838/16692466/ef4bf008-44fe-11e6-8eec-49829416354c.png">

If so, where does it live?

**Comment by rebeccakross** [comment]
It is, to the best of my knowledge, at least up thru the website update. It can be found in Civi > Adminster > Message Templates > System Workflow. Let me know if you can't find it.

**Comment by rebeccakross** [comment]
Tiny update: It can be found in Civi > Adminster > Communications > Message Templates > System Workflow
