### ISSUE TITLE
please help format/finalize 3d post

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/communications#19]
It's in draft here: https://creativecommons.org/?p=50594&preview=true

Can you make sure the #'s show up? They seem to show up as bullets in preview. Everything else looks good to me I think? 

Don't publish yet-- I'll do that.

**Comment by little-wow** [comment]
Fixed the bullets.

Do you want this post to be featured?

**Comment by janetpkr** [comment]
Is there a way to put space between the #ed objects? It looks cramped to
the eye.

On Thu, Jul 14, 2016 at 1:23 PM, Jennie Rose Halperin <
notifications@github.com> wrote:

> Assigned #19 https://github.com/creativecommons/communications/issues/19
> to @janeatcc https://github.com/janeatcc.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/creativecommons/communications/issues/19#event-723537384,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGGTmQ7q0z8ONuI2De4QAHSPO9ZwvVTrks5qVprBgaJpZM4JMzZ1
> .

## 

Jane Park
Director of Platforms and Partnerships
Creative Commons
@janedaily

Get updates: http://bit.ly/commonsnews
Invest in the commons: https://donate.creativecommons.org/

**Comment by janetpkr** [comment]
And yes, would be great to be featured -- once we publish. I'll let you
know when that happens.

On Thu, Jul 14, 2016 at 1:29 PM, Jane Park janepark@creativecommons.org
wrote:

> Is there a way to put space between the #ed objects? It looks cramped to
> the eye.
> 
> On Thu, Jul 14, 2016 at 1:23 PM, Jennie Rose Halperin <
> notifications@github.com> wrote:
> 
> > Assigned #19
> > https://github.com/creativecommons/communications/issues/19 to
> > @janeatcc https://github.com/janeatcc.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/creativecommons/communications/issues/19#event-723537384,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AGGTmQ7q0z8ONuI2De4QAHSPO9ZwvVTrks5qVprBgaJpZM4JMzZ1
> > .
> 
> ## 
> 
> Jane Park
> Director of Platforms and Partnerships
> Creative Commons
> @janedaily
> 
> Get updates: http://bit.ly/commonsnews
> Invest in the commons: https://donate.creativecommons.org/

## 

Jane Park
Director of Platforms and Partnerships
Creative Commons
@janedaily

Get updates: http://bit.ly/commonsnews
Invest in the commons: https://donate.creativecommons.org/

**Comment by little-wow** [comment]
Better?

**Comment by little-wow** [comment]
(you put spaces in with SHIFT + ENTER)

**Comment by janetpkr** [comment]
Yes! Thanks for the tip.

On Thu, Jul 14, 2016 at 1:41 PM, Jennie Rose Halperin <
notifications@github.com> wrote:

> (you put spaces in with SHIFT + ENTER)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/creativecommons/communications/issues/19#issuecomment-232785861,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGGTmZl4ZSV31CnFxxkL6dcI-MvpKnf2ks5qVp7vgaJpZM4JMzZ1
> .

## 

Jane Park
Director of Platforms and Partnerships
Creative Commons
@janedaily

Get updates: http://bit.ly/commonsnews
Invest in the commons: https://donate.creativecommons.org/
