### ISSUE TITLE
add Juliana Monteiro as blog post author

### ISSUE THREAD

**Issue by tvol** [creativecommons/communications#20]
She's one of the Institute for Open Leadership fellows, and I'm helping her edit the blog post about her project. Thanks!

**Comment by little-wow** [comment]
She's added to the blog. Just let me know when you want to publish so that we can time it. Thanks!

**Comment by tvol** [comment]
Thanks. I changed to her name as author but it does not appear on preview.

**Comment by little-wow** [comment]
Can you screenshot?

**Comment by tvol** [comment]
<img width="722" alt="screen shot 2016-07-15 at 1 48 18 pm" src="https://cloud.githubusercontent.com/assets/231665/16888125/db53f32c-4a92-11e6-9a44-b9b4408fdb01.png">

**Comment by tvol** [comment]
<img width="912" alt="screen shot 2016-07-15 at 1 48 31 pm" src="https://cloud.githubusercontent.com/assets/231665/16888136/e6c02ed8-4a92-11e6-8b10-a7d40cc48a60.png">

**Comment by little-wow** [comment]
I just loled a little because the post begins "My name is Juliana Monteiro" with your picture above it and it's late on a Friday.

Let me look at this, one sec.

**Comment by little-wow** [comment]
That's weird.  Maybe it's a problem with the plugin?  I've changed other users on the blog with no problem.
@mattl here are some more screenshots:

<img width="1064" alt="screen shot 2016-07-15 at 4 53 57 pm" src="https://cloud.githubusercontent.com/assets/7093838/16888241/d0d7d854-4aac-11e6-986b-ada597d28e66.png">

<img width="979" alt="screen shot 2016-07-15 at 4 55 07 pm" src="https://cloud.githubusercontent.com/assets/7093838/16888258/e840b2e0-4aac-11e6-9221-63e522abd553.png">

and then plus I'm seeing the same thing as Tim.

**Comment by tvol** [comment]
if there's no fix for this i'm just gonna post it under my name in the typical way we've been handling these. looks like Wordpress also broke my image links. dumb.

**Comment by mattl** [comment]
let me take a look
