### ISSUE TITLE
What happened to the styles on this page?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/communications#28]
It looks different than when I posted it :(
https://creativecommons.org/2016/07/27/makemypattern/

**Comment by mattl** [comment]
What were the styles? Inline CSS?

**Comment by little-wow** [comment]
It was posted like a regular blog post and the images aligned and now they don't 
<img width="883" alt="screen shot 2016-08-03 at 2 31 05 pm" src="https://cloud.githubusercontent.com/assets/7093838/17377270/ffbd3b4e-5986-11e6-9fa2-4936efa5ba14.png">

**Comment by mattl** [comment]
Yeah, the alignment in the WP editor isn't the same as the text due to font sizes, etc.

I moved the image down a little and it looks okay now. Nothing changed on the site other than the CSS changes for the homepage sign up, and those other small issues for the blog. Nothing that would effect this.
