### ISSUE TITLE
can't get link preview when trying to post CC links to Facebook page

### ISSUE THREAD

**Issue by tvol** [creativecommons/communications#29]
<img width="646" alt="screen shot 2016-08-03 at 9 29 38 am" src="https://cloud.githubusercontent.com/assets/231665/17373463/21a99d4e-595d-11e6-94aa-e09abeb82f76.png">

**Comment by little-wow** [comment]
This is a @mattl issue

**Comment by mattl** [comment]
@tvol this happens occasionally. shouldn't happen most of the time. you can always force a new version by adding ?tvol=awesome or some other text after the ? on the end.

**Comment by tvol** [comment]
@mattl ok thanks that works
