### ISSUE TITLE
review blog post about Federal Source Code Policy

### ISSUE THREAD

**Issue by tvol** [creativecommons/communications#31]
at https://docs.google.com/document/d/1kFR5bnErxaziUJU8U-7WI-HLAj8132k5v1-HWT3dk3o/edit @little-wow @peterspdx can you take a look?

**Comment by little-wow** [comment]
I made some comments...  I'm not sure what the audience of this piece is, but IMO it focuses a bit too much on what didn't happen rather than what did happen. If this is a piece to wrap it up for legal, then feel free to ignore my comments.

**Comment by tvol** [comment]
@little-wow thanks for the good feedback. I'm gonna add a bit more context to the post, which I think will help. It's a weak win, so i think it is worthwhile to also say what didn't happen, and keep asking pertinent questions about some of the issues we raised in our comments.

**Comment by tvol** [comment]
done https://creativecommons.org/2016/08/16/u-s-moves-ahead-limited-code-sharing-policy/
