### ISSUE TITLE
please review blog post on European Commission leaked copyright plan

### ISSUE THREAD

**Issue by tvol** [creativecommons/communications#38]
hi @little-wow can you please review and provide any comments or edits you have to this draft post? https://docs.google.com/document/d/1kTP27XV5foPp9c--i-CfVfwgSXoH0qmuCoEka2JQHh0/edit

I'd like for it to be published tomorrow. thanks.

**Comment by little-wow** [comment]
I made some edits-- mostly coming at this from a non-insider point of view, I would need more context on it. Also the post could be much shorter.

**Comment by tvol** [comment]
ok thanks for being my editor, @little-wow. i appreciate it

**Comment by tvol** [comment]
done https://creativecommons.org/2016/08/30/leaked-european-commission-copyright-plans-ignore-public-interest/
