### ISSUE TITLE
review blog post on EC copyright proposal release

### ISSUE THREAD

**Issue by tvol** [creativecommons/communications#40]
@little-wow @ericsteuer  https://docs.google.com/document/d/1hRkeXBtNaFx9zO-8aKvUA-VXA-R5HN9OK_o_sBgyynk/edit

I think we should have this essentially ready to go at around the time the announcement is made tomorrow. I heard that the text of the directive will be made at 1230p CET, with a press conference/formal announcement at 330p CET. We should also be highlighting the statements that will come from other persons and orgs, including Communia, Julia Reda, OpenMedia, EDRi, C4C, Mozilla, etc, likely by RT on Twitter. This is the minimum for tomorrow. If we want we should focus on drafting a short op-ed tomorrow for pitching to EU press for publishing by end of week.

**Comment by little-wow** [comment]
I did edits on it, so feel free to look at it whenever @tvol and I will hop into action.

**Comment by tvol** [comment]
Done, thanks. https://creativecommons.org/2016/09/14/european-commission-copyright-proposal-leaves-users-dark/
